version: '3.8'
services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    links:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb/booksDatabase
  frontend:
    build: ./client
    ports:
      - "80:80"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
